apiVersion: batch/v1
kind: Job
metadata:
  name: ${CUSTER_REGION}-${CITY_LOWER}-devices
spec:
  template:
    metadata:
      labels:
        app: ${CUSTER_REGION}-${CITY_LOWER}-devices
    spec:
      restartPolicy: Never
      containers:
      - name: ${CUSTER_REGION}-devices-${CITY_LOWER}
        image: eu.gcr.io/onboard-2018/iot-device-generic:1.0.3
        command: ["/bin/bash", "14_device_client_run_py.sh", "${CITY}", "${REGISTRY_NAME}", "${DEVICE_NAME}", "${IOT_ZONE}" ]
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
